"""ch15

Revision ID: 561734804faa
Revises: f205124ef891
Create Date: 2025-11-19 16:13:50.340659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561734804faa'
down_revision = 'f205124ef891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
